M48
; DRILL file KiCad 10.0.6 date 2026-09-13T17:41:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T17:41:37+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X127.505Y-63.055
X132.505Y-63.055
T2
X101.17Y-69.5
X101.17Y-72.5
T3
X102.0Y-61.0
X102.0Y-103.0
X140.0Y-61.0
X140.0Y-103.0
M30
